version: '3'
services:
  incident-api:
    image: incident-mgr:0.0.1-SNAPSHOT
    platform: linux/amd64
    ports:
      - "8080:8082"
      - "5005:5005"
    environment:
      # Used only when the value are specific to the environment.
      - SERVER_PORT=8082
      # By default, the application will use the H2 in-memory database.
      - SPRING_PROFILES_ACTIVE=h2
      # so as to allow remote debugging
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  # Only used to verify if the application is up and running with PG as storage.
  incident-postgres:
    image: "postgres:14-alpine"
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=incident
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
