spring:
  application:
    name: incident-mgr
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=10m
  jpa:
    # Better control transaction scope explicitly.
    open-in-view: false
  data:
    rest:
      base-path: /rest
  jackson:
    serialization:
      write-dates-as-timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: info, flyway, health, metrics, threaddump, loggers, mappings, caches, prometheus
